name: main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm ci
      - uses: cycjimmy/semantic-release-action@v5
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 18.0.1
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
          branches: main
      - id: package-version
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        if: steps.semantic.outputs.new_release_published == 'true'
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: web
          ITCH_GAME: borksy
          ITCH_USER: ayolland
          PACKAGE: docs
          VERSION: ${{ steps.package-version.outputs.current-version}}
