name: main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git config --global user.name '${{ github.actor }}'
      - run: git config --global user.email '${{ github.actor }}@users.noreply.github.com'
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      - uses: mukunku/tag-exists-action@v1.0.0
        id: tag-exists
        with: 
          tag: v${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm version patch
        if: steps.tag-exists.outputs.exists == 'true'
      - run: git tag v${{ steps.package-version.outputs.current-version }}
      - run: npm run build
      - run: git add docs package.json
      - run: git commit --allow-empty -m "update build [skip ci]"
      - run: git push --tags
      - uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: web
          ITCH_GAME: borksy
          ITCH_USER: ayolland
          PACKAGE: docs
          VERSION: ${{ steps.package-version.outputs.current-version}}
