name: main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      - uses: mukunku/tag-exists-action@v1.0.0
        id: tag-exists
        with: 
          tag: ${{ steps.package-version.outputs.current-version}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm version patch
        if: steps.tag-exists.outputs.exists == 'true'
      - run: npm run build
      - uses: EndBug/add-and-commit@v7.3.0
        with:
          add: 'docs'
          message: 'update build [skip ci]'
      - uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: web
          ITCH_GAME: borksy
          ITCH_USER: ayolland
          PACKAGE: docs
          VERSION: ${{ steps.package-version.outputs.current-version}}
