name: release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      - uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: web
          ITCH_GAME: borksy
          ITCH_USER: ayolland
          PACKAGE: docs
          VERSION: ${{ steps.package-version.outputs.current-version }}
